### ISSUE TITLE
Problem with save-lisp-and-die

### ISSUE THREAD

**Issue by bpecsek** [marcoheisig/sb-simd#10]
I am trying to save image and getting this:

debugger invoked on a TYPE-ERROR @52E31913 in thread
#<THREAD "main thread" RUNNING {1001870103}>:
  The value
    -1
  is not of type
    (UNSIGNED-BYTE 16)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-VM::%SIMPLE-FUN-FROM-ENTRYPOINT #<code id=AF0C [1] (SB-C::VOP SB-SIMD-AVX2::%TWO-ARG-S8.32-XOR) {53619FEF}> 1398906872)
0]

**Comment by marcoheisig** [comment]
This is a bug in SBCL:  https://bugs.launchpad.net/sbcl/+bug/1942191

**Comment by bpecsek** [comment]
Hi Marco,

Any progress with this?
I've seen that it might not be an SBCL issue.

Kindest Regards,
Bela

**Comment by marcoheisig** [comment]
I'm narrowing it down right now.

**Comment by bpecsek** [comment]
Sorry for asking again but any progress yet?
I would need to save a demo application and I can't showcase it this way.
I hope it will be fixed before the Uni starts.

**Comment by marcoheisig** [comment]
This is the weirdest bug I have encountered in a long time.  I cannot even track it down to a particular line of code.  There seems to be some threshold of certain SIMD function definitions after which `save-lisp-and-die` breaks down, but I haven't managed to find the culprit.

As a workaround, you can build SBCL with `--without-immobile-code`.  That should avoid that problem altogether.

**Comment by bpecsek** [comment]
Thanks Marco,

This must be a tough one! Some bugs like cockroaches are hard to kill:)
For my demo I can build SBCL with the switch.

I have 100% trust in you that you figure it out.
I am very sorry that I can’t assist you this time but I am in and out of hospital and I still don’t know how bad my health issue really is. Fingers crossed though.

**Comment by marcoheisig** [comment]
Done.  I just submitted a fix to SBCL: https://bugs.launchpad.net/sbcl/+bug/1942191/comments/5

**Comment by bpecsek** [comment]
Perfect! So it was indeed an sbcl bug.
You are the best.
Would it be possible to include the fix in sb-simd until sbcl-2.1.9 is released with the fix?

**Comment by bpecsek** [comment]
Hi Marco,

I have started to do some benchmark on a [site](https://programming-language-benchmarks.vercel.app/) that use more modern processors then the Computer Language Benchmark Game and I am pleased to say that sb-simd is running very nicely indeed. The code runs on sbc-2.1.8 with your patch applied.

Look at the speed of my [spectralnorm #2](https://programming-language-benchmarks.vercel.app/problem/spectral-norm) code! Quite impressive.

**Comment by marcoheisig** [comment]
This is great news and a wonderful motivation!

I wonder if there are still some unnecessary SSE<->AVX transitions in the code, though.  The good news that this is something I plan to address next.  So far, I patch each individual VOP emitter in SBCL to either emit a VEX prefix or not.  But I think it would be much more robust and elegant to simply change the assembler to take care of the VEX prefix without touching any VOPs.  Stay tuned for updates :)
