### ISSUE TITLE
FMA

### ISSUE THREAD

**Issue by bpecsek** [marcoheisig/sb-simd#14]
Hi Marco,

Are you planning to add FMA?

Regards,
Bela

**Comment by marcoheisig** [comment]
Yes, I am planning to add FMA.  I am also contemplating an optimization pass in the vectorizer that automatically converts consecutive mul and add instructions to FMA when appropriate.

Right now, the main issue is to write some code that detects whether FMA is present or not.  Do you have any ideas for that?

**Comment by marcoheisig** [comment]
Nevermind, I figured it out.  I will define a cpuid VOP on x86-64 and use it to query CPU features.  With that settled, I can add FMA soon.

**Comment by marcoheisig** [comment]
CPU feature detection just landed: 25b9bef1ea12ff5712f275393d22c830244fb224.

FMA is next on my list :)

**Comment by bpecsek** [comment]
Cool
Looking forward to see FMA added.
Improvement in the vectorizer is always welcomed for sure.

**Comment by marcoheisig** [comment]
Done.  FMA landed in fed2592095f1b89b6fdf429950c0ff0ad638f47c.
