### ISSUE TITLE
Indexing multidimensional arrays is broken

### ISSUE THREAD

**Issue by moon-chilled** [marcoheisig/sb-simd#19]
The following code errors, but should work:

```lisp
(let ((x (make-array '(8 8 8) :element-type 'double-float :initial-element 0d0)))
  (format t "~a~%" (f64.4-aref x 4 4 4)))
```

**Comment by marcoheisig** [comment]
Thanks for spotting this!  Fixed in 30042ceff04bfd79fcee0f7700136b59d0c3ba9a.

Once again, I'm thinking of defining `let` as an alias to `let*` in all of my codes :)
